---
- name: Deploy Whanos Infrastructure
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    # - base           
    - docker           
    - jenkins        
    - kubernetes

