apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: docker.io/2fic/whanos-base-javascript:latest
        ports:
        - containerPort: 3000  # Matches the application's exposed port
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80          # External port to expose the service
      targetPort: 3000  # Port inside the container
  type: NodePort
