FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

COPY . .

RUN echo "Contents of /app:" && ls -la /app

RUN mvn dependency:resolve -f app/pom.xml \
        && mvn package -f app/pom.xml \
        && cp app/target/app.jar . \
        && rm -rf app/

CMD ["java", "-jar", "app.jar"]