FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

ONBUILD COPY . .
ONBUILD RUN echo "Contents of /app:" && ls -la /app
ONBUILD RUN mvn dependency:resolve -f app/pom.xml \
        && mvn package -f app/pom.xml \
        && cp app/target/app.jar . \
        && rm -rf app/

ONBUILD CMD ["java", "-jar", "app.jar"]
