jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Administrator"
          password: "root"
  authorizationStrategy:  
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos administrator"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - file: "/var/lib/jenkins/job_dsl.groovy"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "git_ssh_key"
              username: "${SSH_KEY_USERNAME}"
              description: "SSH key for Git."
              privateKeySource:
                directEntry:
                  privateKey: "${SSH_PRIVATE_KEY}"
