- name: Ensure curl is installed
  become: true
  pacman:
    name: curl
    state: present
    update_cache: yes

- name: Download and install k3s
  become: true
  shell:
    cmd: |
      curl -sfL https://get.k3s.io | sh -
    creates: /usr/local/bin/k3s

- name: Install yq
  become: true
  ansible.builtin.shell: |
    wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
    chmod +x /usr/bin/yq
  args:
    creates: /usr/bin/yq

- name: Wait for k3s service to become active
  retries: 5
  delay: 10
  become: true
  shell: systemctl is-active --quiet k3s
  register: k3s_active
  until: k3s_active.rc == 0

- name: Verify k3s installation
  become: true
  command: k3s kubectl get nodes
  register: k3s_nodes

- name: Ensure k3s service is running
  become: true
  service:
    name: k3s
    state: started
    enabled: true

- name: Create .kube directory for Jenkins
  become: true
  file:
    path: /var/lib/jenkins/.kube
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'
  
- name: Copy k3s config to Jenkins user directory
  become: true
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /var/lib/jenkins/.kube/config
    remote_src: yes
    owner: jenkins
    group: jenkins
    mode: '0600'

- name: Replace localhost in Jenkins kubeconfig
  become: true
  replace:
    path: /var/lib/jenkins/.kube/config
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ inventory_hostname }}:6443'

- name: Debug k3s setup
  debug:
    msg: >
      k3s has been successfully installed and configured. Node(s) detected:
      {{ k3s_nodes.stdout_lines }}
