FROM ubuntu:devel

SHELL [ "/bin/bash", "-c" ]

RUN apt-get update && apt-get install -y \
    make \
    gcc \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/catseye/Befunge-93.git

RUN cd Befunge-93 && gcc -o befunge src/bef.c

WORKDIR /app

ONBUILD COPY . /app

ONBUILD CMD [ "/Befunge-93/befunge", "app/main.bf" ]