- name: Update system repository index
  become: true
  pacman:
    update_cache: yes

- name: Install Git
  become: true
  pacman:
    name: git
    state: present

- name: Install Python and required packages
  become: true
  pacman:
    name:
      - python
      - python-pip
      - python-setuptools
    state: present
